eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  ignored-services: "*"
  routes:
    web-item-service:
      path: /view/**
      service-id: web-view-service
    web-auth-service:
      path: /auth/**
      service-id: web-auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    web-shop-cart-service:
      path: /cart/**
      service-id: web-shop-cart-service
      strip-prefix: false
    web-member-service:
      path: /member/**
      service-id: web-member-service
      strip-prefix: false
    web-order-service:
      path: /order/**
      service-id: web-order-service
      strip-prefix: false
    web-es-service:
      path: /es/**
      service-id: web-es-service
      strip-prefix: false


spring:
  profiles:
    active: dev